# Generated by Django 5.2.10 on 2026-02-27 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('refinery', 'Refinery'), ('pipeline', 'Pipeline'), ('compressor', 'Compressor'), ('terminal', 'Terminal'), ('well', 'Well'), ('gas_plant', 'Gas Plant'), ('tank_battery', 'Tank Battery'), ('other', 'Other')], max_length=32)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('operator', models.CharField(max_length=255)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'db_table': 'facilities',
                'ordering': ['facility_id'],
            },
        ),
        migrations.CreateModel(
            name='MethaneHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_index', models.CharField(db_index=True, max_length=64, unique=True)),
                ('count', models.IntegerField(help_text='Observation count (proxy for CH4 column density)')),
                ('label', models.IntegerField(default=1)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('severity', models.CharField(blank=True, choices=[('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'methane_hotspots',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='demo', help_text='demo or live', max_length=16)),
                ('use_llm', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('total_hotspots', models.IntegerField(default=0)),
                ('detected_hotspots_count', models.IntegerField(default=0)),
                ('plumes_count', models.IntegerField(default=0)),
                ('attributions_count', models.IntegerField(default=0)),
                ('reports_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pipeline_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttributedEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(help_text='Distance between plume and facility in km')),
                ('confidence', models.CharField(choices=[('high', 'High (<500m)'), ('medium', 'Medium (<2km)'), ('low', 'Low (>2km)')], max_length=16)),
                ('emission_rate_kg_hr', models.FloatField()),
                ('attributed_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='api.facility')),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='api.pipelinerun')),
            ],
            options={
                'db_table': 'attributed_emissions',
                'ordering': ['-emission_rate_kg_hr'],
            },
        ),
        migrations.CreateModel(
            name='InversionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_q_kg_hr', models.FloatField(help_text='Estimated emission rate (kg/hr)')),
                ('estimated_q_kg_s', models.FloatField(help_text='Estimated emission rate (kg/s)')),
                ('true_q_kg_hr', models.FloatField(blank=True, null=True)),
                ('error_pct', models.FloatField(blank=True, help_text='Percentage error vs true', null=True)),
                ('ci_lower_kg_hr', models.FloatField(help_text='95% CI lower bound')),
                ('ci_upper_kg_hr', models.FloatField(help_text='95% CI upper bound')),
                ('final_loss', models.FloatField()),
                ('n_iterations', models.IntegerField()),
                ('converged', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('attribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inversion', to='api.attributedemission')),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inversions', to='api.pipelinerun')),
            ],
            options={
                'db_table': 'inversion_results',
                'ordering': ['-estimated_q_kg_hr'],
            },
        ),
        migrations.CreateModel(
            name='DetectedHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('ch4_count', models.IntegerField()),
                ('anomaly_score', models.FloatField()),
                ('severity', models.CharField(max_length=16)),
                ('requires_highres', models.BooleanField(default=False)),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Moderate')], default=3)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('source_hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='api.methanehotspot')),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detected_hotspots', to='api.pipelinerun')),
            ],
            options={
                'db_table': 'detected_hotspots',
                'ordering': ['priority', '-anomaly_score'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('emission_rate_kg_hr', models.FloatField()),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=16)),
                ('confidence', models.CharField(max_length=16)),
                ('report_markdown', models.TextField(help_text='Full markdown report content')),
                ('executive_summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('attribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.attributedemission')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.facility')),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.pipelinerun')),
            ],
            options={
                'db_table': 'audit_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlumeObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plume_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('emission_rate_kg_hr', models.FloatField(help_text='Emission rate in kg/hr')),
                ('wind_speed_ms', models.FloatField(help_text='Wind speed in m/s')),
                ('wind_direction_deg', models.FloatField(help_text='Wind direction in degrees')),
                ('plume_length_m', models.FloatField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=64)),
                ('concentration_ppm', models.FloatField(blank=True, null=True)),
                ('is_synthetic', models.BooleanField(default=True, help_text='True if generated, False if from API')),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plumes', to='api.pipelinerun')),
            ],
            options={
                'db_table': 'plume_observations',
                'ordering': ['-emission_rate_kg_hr'],
            },
        ),
        migrations.AddField(
            model_name='attributedemission',
            name='plume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='api.plumeobservation'),
        ),
        migrations.CreateModel(
            name='TaskingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('satellite', models.CharField(default='CarbonMapper-Tanager', max_length=64)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Moderate')], default=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('acquired', 'Acquired'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasking_requests', to='api.detectedhotspot')),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasking_requests', to='api.pipelinerun')),
            ],
            options={
                'db_table': 'tasking_requests',
                'ordering': ['priority', '-requested_at'],
            },
        ),
    ]
