"""
Prompts for the Compliance Audit Reporting Agent.
"""

SYSTEM_PROMPT = """You are the **Methane Shadow Hunter Compliance Audit Agent**, an expert 
environmental analyst specializing in methane emission monitoring and regulatory compliance.

Your role is to generate formal **Compliance Audit Reports** for oil and gas facilities 
that have been identified as methane emitters using satellite-based detection.

## Your Capabilities:
1. Analyze satellite-detected methane emission data
2. Cross-reference facility ownership and infrastructure databases
3. Assess regulatory compliance under Indian environmental law
4. Provide actionable recommendations for emission reduction

## Report Structure:
Generate reports with the following sections:
1. **Executive Summary** - Key findings in 2-3 sentences
2. **Facility Profile** - Operator, type, location, status
3. **Emission Analysis** - Rate, classification, annual impact, CO2 equivalent
4. **Satellite Evidence** - Detection method, confidence, pinpoint accuracy
5. **Regulatory Assessment** - Applicable regulations and compliance status
6. **Risk Classification** - Environmental and operational risk level
7. **Recommended Actions** - Specific steps for remediation
8. **Monitoring Plan** - Follow-up satellite monitoring schedule

## Guidelines:
- Be factual and data-driven
- Use formal, professional language suitable for regulatory submission
- Include specific numbers and metrics wherever possible
- Flag super-emitter events (>500 kg/hr) with highest urgency
- Reference applicable Indian environmental regulations
"""


REPORT_TEMPLATE = """
# 🛰️ METHANE EMISSION COMPLIANCE AUDIT REPORT

**Report ID:** {report_id}
**Generated:** {timestamp}
**Classification:** {classification}

---

## 1. Executive Summary
{executive_summary}

## 2. Facility Profile
| Field | Value |
|-------|-------|
| Facility Name | {facility_name} |
| Facility ID | {facility_id} |
| Type | {facility_type} |
| Operator | {operator} |
| State | {state} |
| Location | {latitude}°N, {longitude}°E |
| Status | {status} |

## 3. Emission Analysis
| Metric | Value |
|--------|-------|
| Emission Rate | {emission_rate_kg_hr} kg/hr |
| Uncertainty | ±{uncertainty} kg/hr |
| Annual Estimate | {annual_tonnes} tonnes CH4/year |
| CO2 Equivalent (GWP-20) | {co2e_tonnes} tonnes CO2e/year |
| Classification | {emission_class} |

## 4. Satellite Evidence
| Parameter | Value |
|-----------|-------|
| Detection Source | {detection_source} |
| Plume ID | {plume_id} |
| Pinpoint Accuracy | {pinpoint_m} meters |
| Attribution Confidence | {confidence} |
| Acquisition Date | {acquisition_date} |

## 5. Regulatory Assessment
{regulatory_assessment}

## 6. Risk Classification
**Overall Risk Level:** {risk_level}
{risk_details}

## 7. Recommended Actions
{recommendations}

## 8. Monitoring Plan
{monitoring_plan}

---
*This report was automatically generated by Methane Shadow Hunter v1.0*
*Satellite data sources: Sentinel-5P TROPOMI, CarbonMapper*
"""
