import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import {
  FileText,
  Download,
  Calendar,
  TrendingDown,
  TrendingUp,
  AlertTriangle,
  CheckCircle,
  BarChart3,
  PieChart,
  Filter,
  RefreshCw,
} from 'lucide-react'
import { Button, GlassCard, Spinner } from '../components/ui/Common'
import { reportsService, dashboardService } from '../services/api'

/**
 * Reports Page
 * Audit reports from pipeline runs
 */
const Reports = () => {
  const [reports, setReports] = useState([])
  const [summary, setSummary] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [expandedReport, setExpandedReport] = useState(null)

  const fetchData = async () => {
    setLoading(true)
    setError(null)
    try {
      const [reportsData, summaryData] = await Promise.all([
        reportsService.getAll({ ordering: '-generated_at' }),
        dashboardService.getSummary(),
      ])
      setReports(Array.isArray(reportsData) ? reportsData : [])
      setSummary(summaryData)
    } catch (err) {
      console.error('Reports fetch error:', err)
      setError('Failed to load reports.')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { fetchData() }, [])

  // View full report markdown
  const viewReport = async (id) => {
    try {
      const full = await reportsService.getById(id)
      setExpandedReport(full)
    } catch (err) {
      console.error('Report detail error:', err)
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <Spinner size="lg" className="text-accent-green" />
      </div>
    )
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="text-center glass-card p-8">
          <AlertTriangle className="w-12 h-12 text-warning-yellow mx-auto mb-4" />
          <p className="text-gray-400 mb-4">{error}</p>
          <button onClick={fetchData} className="text-accent-green hover:underline">Retry</button>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3">
            <FileText className="w-7 h-7 text-accent-green" />
            Audit Reports
          </h1>
          <p className="text-gray-400 mt-1">
            Compliance audit reports generated by the pipeline
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="outline" icon={RefreshCw} size="sm" onClick={fetchData}>
            Refresh
          </Button>
        </div>
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="glass-card p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-info-blue/20">
              <BarChart3 className="w-5 h-5 text-info-blue" />
            </div>
            <div>
              <p className="text-xs text-gray-500">Total Reports</p>
              <p className="text-xl font-bold text-white">{summary?.total_reports || reports.length}</p>
            </div>
          </div>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="glass-card p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-danger-red/20">
              <AlertTriangle className="w-5 h-5 text-danger-red" />
            </div>
            <div>
              <p className="text-xs text-gray-500">Critical</p>
              <p className="text-xl font-bold text-white">{reports.filter(r => r.risk_level === 'critical').length}</p>
            </div>
          </div>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="glass-card p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-warning-yellow/20">
              <PieChart className="w-5 h-5 text-warning-yellow" />
            </div>
            <div>
              <p className="text-xs text-gray-500">High Risk</p>
              <p className="text-xl font-bold text-white">{reports.filter(r => r.risk_level === 'high').length}</p>
            </div>
          </div>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-card p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-accent-green/20">
              <CheckCircle className="w-5 h-5 text-accent-green" />
            </div>
            <div>
              <p className="text-xs text-gray-500">Facilities</p>
              <p className="text-xl font-bold text-white">{summary?.total_facilities || 0}</p>
            </div>
          </div>
        </motion.div>
      </div>

      {/* Reports List */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
        className="glass-card"
      >
        <div className="p-4 border-b border-dark-border">
          <h3 className="text-lg font-semibold text-white">Audit Reports</h3>
          <p className="text-sm text-gray-400">Click to view full compliance report</p>
        </div>

        <div className="divide-y divide-dark-border/50">
          {reports.length === 0 ? (
            <div className="p-12 text-center">
              <FileText className="w-12 h-12 text-gray-600 mx-auto mb-3" />
              <p className="text-gray-400">No reports yet. Run the pipeline to generate audit reports.</p>
            </div>
          ) : (
            reports.map((report, index) => (
              <motion.div
                key={report.report_id || report.id}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.1 + index * 0.05 }}
                className="p-4 flex items-center justify-between hover:bg-dark-border/20 transition-colors cursor-pointer"
                onClick={() => viewReport(report.id)}
              >
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-xl bg-accent-green/10 flex items-center justify-center">
                    <FileText className="w-6 h-6 text-accent-green" />
                  </div>
                  <div>
                    <h4 className="font-medium text-white">{report.report_id}</h4>
                    <div className="flex items-center gap-4 mt-1">
                      <span className="text-xs text-gray-500 flex items-center gap-1">
                        <AlertTriangle className="w-3 h-3" />
                        Risk: {report.risk_level}
                      </span>
                      <span className="text-xs text-gray-500 flex items-center gap-1">
                        <Calendar className="w-3 h-3" />
                        {report.generated_at ? new Date(report.generated_at).toLocaleDateString() : 'N/A'}
                      </span>
                      {report.facility_name && (
                        <span className="text-xs text-gray-500">
                          Facility: {report.facility_name}
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <div className={`flex items-center gap-2 px-3 py-1 rounded-full ${
                    report.risk_level === 'critical' ? 'bg-danger-red/10' :
                    report.risk_level === 'high' ? 'bg-warning-yellow/10' :
                    'bg-accent-green/10'
                  }`}>
                    <div className={`w-2 h-2 rounded-full ${
                      report.risk_level === 'critical' ? 'bg-danger-red' :
                      report.risk_level === 'high' ? 'bg-warning-yellow' :
                      'bg-accent-green'
                    }`} />
                    <span className={`text-xs font-medium ${
                      report.risk_level === 'critical' ? 'text-danger-red' :
                      report.risk_level === 'high' ? 'text-warning-yellow' :
                      'text-accent-green'
                    }`}>{report.risk_level}</span>
                  </div>
                </div>
              </motion.div>
            ))
          )}
        </div>
      </motion.div>

      {/* Expanded Report Modal */}
      {expandedReport && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4"
          onClick={() => setExpandedReport(null)}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="glass-card w-full max-w-4xl max-h-[90vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="p-6 border-b border-dark-border flex items-center justify-between">
              <div>
                <h2 className="text-xl font-bold text-white">{expandedReport.report_id}</h2>
                <p className="text-sm text-gray-400">Risk Level: {expandedReport.risk_level}</p>
              </div>
              <button onClick={() => setExpandedReport(null)} className="p-2 hover:bg-dark-border rounded-lg">
                <span className="text-gray-400 hover:text-white text-xl">✕</span>
              </button>
            </div>
            <div className="p-6">
              <pre className="whitespace-pre-wrap text-sm text-gray-300 font-mono leading-relaxed">
                {expandedReport.report_markdown || 'No content available.'}
              </pre>
            </div>
          </motion.div>
        </motion.div>
      )}
    </div>
  )
}

export default Reports
