import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  FileText,
  Download,
  Calendar,
  TrendingDown,
  TrendingUp,
  AlertTriangle,
  CheckCircle,
  BarChart3,
  PieChart,
  Filter,
  RefreshCw,
  Play,
  ChevronDown,
  CheckCircle2,
  XCircle,
} from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { Button, GlassCard, Spinner } from '../components/ui/Common'
import { reportsService, dashboardService, pipelineService } from '../services/api'

/**
 * Reports Page
 * Audit reports from pipeline runs
 */
const Reports = () => {
  const [reports, setReports] = useState([])
  const [summary, setSummary] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [expandedReport, setExpandedReport] = useState(null)

  // Pipeline trigger state
  const [pipelineRunning, setPipelineRunning] = useState(false)
  const [pipelineStatus, setPipelineStatus] = useState(null)
  const [pipelineMsg, setPipelineMsg] = useState('')
  const [modeMenuOpen, setModeMenuOpen] = useState(false)

  const fetchData = async () => {
    setLoading(true)
    setError(null)
    try {
      const [reportsData, summaryData] = await Promise.all([
        reportsService.getAll({ ordering: '-generated_at' }),
        dashboardService.getSummary(),
      ])
      setReports(Array.isArray(reportsData) ? reportsData : [])
      setSummary(summaryData)
    } catch (err) {
      console.error('Reports fetch error:', err)
      setError('Failed to load reports.')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { fetchData() }, [])

  const runPipeline = async (mode = 'demo') => {
    setModeMenuOpen(false)
    setPipelineRunning(true)
    setPipelineStatus(null)
    setPipelineMsg(`Starting pipeline in ${mode} mode…`)
    try {
      const { run_id } = await pipelineService.trigger(mode)
      setPipelineMsg(`Pipeline running (ID: ${run_id}) — polling for results…`)
      const result = await pipelineService.pollRun(run_id, {
        onProgress: (run) => {
          if (run.plumes_count) setPipelineMsg(`Running… ${run.plumes_count} plumes processed`)
        },
      })
      setPipelineStatus('success')
      setPipelineMsg(
        `Pipeline complete — ${result.reports_count ?? 0} new reports generated`
      )
      await fetchData()
    } catch (err) {
      setPipelineStatus('error')
      setPipelineMsg(err?.response?.data?.error || err.message || 'Pipeline failed')
    } finally {
      setPipelineRunning(false)
    }
  }

  // View full report markdown
  const viewReport = async (id) => {
    try {
      const full = await reportsService.getById(id)
      setExpandedReport(full)
    } catch (err) {
      console.error('Report detail error:', err)
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <Spinner size="lg" className="text-accent-green" />
      </div>
    )
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="text-center glass-card p-8">
          <AlertTriangle className="w-12 h-12 text-warning-yellow mx-auto mb-4" />
          <p className="text-gray-400 mb-4">{error}</p>
          <button onClick={fetchData} className="text-accent-green hover:underline">Retry</button>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3">
            <FileText className="w-7 h-7 text-accent-green" />
            Audit Reports
          </h1>
          <p className="text-gray-400 mt-1">
            Compliance audit reports generated by the pipeline
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="outline" icon={RefreshCw} size="sm" onClick={fetchData}>
            Refresh
          </Button>

          {/* Run Pipeline split-button */}
          <div className="relative">
            <div className="flex items-center">
              <button
                onClick={() => runPipeline('demo')}
                disabled={pipelineRunning}
                className="flex items-center gap-2 px-4 py-2 bg-accent-green hover:bg-accent-green/80 disabled:opacity-60 disabled:cursor-not-allowed text-white rounded-l-lg transition-colors text-sm font-medium"
              >
                {pipelineRunning
                  ? <Spinner size="sm" className="text-white" />
                  : <Play className="w-4 h-4" />}
                {pipelineRunning ? 'Running…' : 'Run Pipeline'}
              </button>
              <button
                onClick={() => setModeMenuOpen(o => !o)}
                disabled={pipelineRunning}
                className="flex items-center px-2 py-2 bg-accent-green/80 hover:bg-accent-green/60 disabled:opacity-60 text-white rounded-r-lg border-l border-white/20 transition-colors"
              >
                <ChevronDown className="w-4 h-4" />
              </button>
            </div>

            <AnimatePresence>
              {modeMenuOpen && (
                <motion.div
                  initial={{ opacity: 0, y: -4 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -4 }}
                  className="absolute right-0 mt-1 w-44 glass-card border border-dark-border rounded-lg shadow-xl z-50 overflow-hidden"
                >
                  <button
                    onClick={() => runPipeline('demo')}
                    className="w-full text-left px-4 py-3 text-sm text-gray-200 hover:bg-accent-green/10 hover:text-accent-green transition-colors"
                  >
                    <span className="font-medium">Demo</span>
                    <p className="text-xs text-gray-500 mt-0.5">Bundled dataset, fast</p>
                  </button>
                  <button
                    onClick={() => runPipeline('live')}
                    className="w-full text-left px-4 py-3 text-sm text-gray-200 hover:bg-accent-green/10 hover:text-accent-green transition-colors border-t border-dark-border"
                  >
                    <span className="font-medium">Live</span>
                    <p className="text-xs text-gray-500 mt-0.5">GEE + CarbonMapper API</p>
                  </button>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </div>

      {/* Pipeline status toast */}
      <AnimatePresence>
        {pipelineMsg && (
          <motion.div
            initial={{ opacity: 0, y: -12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -12 }}
            className={`flex items-center gap-3 px-4 py-3 rounded-lg text-sm ${
              pipelineRunning
                ? 'bg-info-blue/10 border border-info-blue/30 text-info-blue'
                : pipelineStatus === 'success'
                ? 'bg-accent-green/10 border border-accent-green/30 text-accent-green'
                : 'bg-danger-red/10 border border-danger-red/30 text-danger-red'
            }`}
          >
            {pipelineRunning
              ? <Spinner size="sm" className="text-info-blue" />
              : pipelineStatus === 'success'
              ? <CheckCircle2 className="w-4 h-4 flex-shrink-0" />
              : <XCircle className="w-4 h-4 flex-shrink-0" />}
            <span>{pipelineMsg}</span>
            {!pipelineRunning && (
              <button onClick={() => setPipelineMsg('')} className="ml-auto opacity-60 hover:opacity-100">✕</button>
            )}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Summary Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="glass-card p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-info-blue/20">
              <BarChart3 className="w-5 h-5 text-info-blue" />
            </div>
            <div>
              <p className="text-xs text-gray-500">Total Reports</p>
              <p className="text-xl font-bold text-white">{summary?.total_reports || reports.length}</p>
            </div>
          </div>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="glass-card p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-danger-red/20">
              <AlertTriangle className="w-5 h-5 text-danger-red" />
            </div>
            <div>
              <p className="text-xs text-gray-500">Critical</p>
              <p className="text-xl font-bold text-white">{reports.filter(r => r.risk_level === 'CRITICAL').length}</p>
            </div>
          </div>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="glass-card p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-warning-yellow/20">
              <PieChart className="w-5 h-5 text-warning-yellow" />
            </div>
            <div>
              <p className="text-xs text-gray-500">High Risk</p>
              <p className="text-xl font-bold text-white">{reports.filter(r => r.risk_level === 'HIGH').length}</p>
            </div>
          </div>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-card p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-accent-green/20">
              <CheckCircle className="w-5 h-5 text-accent-green" />
            </div>
            <div>
              <p className="text-xs text-gray-500">Facilities</p>
              <p className="text-xl font-bold text-white">{summary?.total_facilities || 0}</p>
            </div>
          </div>
        </motion.div>
      </div>

      {/* Reports List */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
        className="glass-card"
      >
        <div className="p-4 border-b border-dark-border">
          <h3 className="text-lg font-semibold text-white">Audit Reports</h3>
          <p className="text-sm text-gray-400">Click to view full compliance report</p>
        </div>

        <div className="divide-y divide-dark-border/50">
          {reports.length === 0 ? (
            <div className="p-12 text-center">
              <FileText className="w-12 h-12 text-gray-600 mx-auto mb-3" />
              <p className="text-gray-400">No reports yet. Run the pipeline to generate audit reports.</p>
            </div>
          ) : (
            reports.map((report, index) => (
              <motion.div
                key={report.report_id || report.id}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.1 + index * 0.05 }}
                className="p-4 flex items-center justify-between hover:bg-dark-border/20 transition-colors cursor-pointer"
                onClick={() => viewReport(report.id)}
              >
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-xl bg-accent-green/10 flex items-center justify-center">
                    <FileText className="w-6 h-6 text-accent-green" />
                  </div>
                  <div>
                    <h4 className="font-medium text-white">{report.report_id}</h4>
                    <div className="flex items-center gap-4 mt-1">
                      <span className="text-xs text-gray-500 flex items-center gap-1">
                        <AlertTriangle className="w-3 h-3" />
                        Risk: {report.risk_level}
                      </span>
                      <span className="text-xs text-gray-500 flex items-center gap-1">
                        <Calendar className="w-3 h-3" />
                        {report.generated_at ? new Date(report.generated_at).toLocaleDateString() : 'N/A'}
                      </span>
                      {report.facility_name && (
                        <span className="text-xs text-gray-500">
                          Facility: {report.facility_name}
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <div className={`flex items-center gap-2 px-3 py-1 rounded-full ${
                    report.risk_level === 'CRITICAL' ? 'bg-danger-red/10' :
                    report.risk_level === 'HIGH' ? 'bg-warning-yellow/10' :
                    'bg-accent-green/10'
                  }`}>
                    <div className={`w-2 h-2 rounded-full ${
                      report.risk_level === 'CRITICAL' ? 'bg-danger-red' :
                      report.risk_level === 'HIGH' ? 'bg-warning-yellow' :
                      'bg-accent-green'
                    }`} />
                    <span className={`text-xs font-medium ${
                      report.risk_level === 'CRITICAL' ? 'text-danger-red' :
                      report.risk_level === 'HIGH' ? 'text-warning-yellow' :
                      'text-accent-green'
                    }`}>{report.risk_level}</span>
                  </div>
                </div>
              </motion.div>
            ))
          )}
        </div>
      </motion.div>

      {/* Expanded Report Modal */}
      {expandedReport && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4"
          onClick={() => setExpandedReport(null)}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="glass-card w-full max-w-4xl max-h-[90vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="p-6 border-b border-dark-border flex items-center justify-between">
              <div>
                <h2 className="text-xl font-bold text-white">{expandedReport.report_id}</h2>
                <p className="text-sm text-gray-400">Risk Level: {expandedReport.risk_level}</p>
              </div>
              <button onClick={() => setExpandedReport(null)} className="p-2 hover:bg-dark-border rounded-lg">
                <span className="text-gray-400 hover:text-white text-xl">✕</span>
              </button>
            </div>
            <div className="p-6 report-markdown">
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                  h1: ({children}) => <h1 className="text-2xl font-bold text-white mt-6 mb-3 pb-2 border-b border-dark-border flex items-center gap-2">{children}</h1>,
                  h2: ({children}) => <h2 className="text-lg font-semibold text-accent-green mt-6 mb-2 pb-1 border-b border-dark-border/50">{children}</h2>,
                  h3: ({children}) => <h3 className="text-base font-semibold text-white mt-4 mb-2">{children}</h3>,
                  p:  ({children}) => <p className="text-gray-300 text-sm leading-relaxed mb-3">{children}</p>,
                  strong: ({children}) => <strong className="text-white font-semibold">{children}</strong>,
                  em: ({children}) => <em className="text-gray-400 italic">{children}</em>,
                  hr: () => <hr className="my-4 border-dark-border" />,
                  ul: ({children}) => <ul className="list-disc list-inside space-y-1 mb-3 text-sm text-gray-300">{children}</ul>,
                  ol: ({children}) => <ol className="list-decimal list-inside space-y-1 mb-3 text-sm text-gray-300">{children}</ol>,
                  li: ({children}) => <li className="text-gray-300 text-sm leading-relaxed">{children}</li>,
                  code: ({inline, children}) => inline
                    ? <code className="bg-dark-border/60 text-accent-green px-1.5 py-0.5 rounded text-xs font-mono">{children}</code>
                    : <pre className="bg-dark-bg/80 border border-dark-border rounded-lg p-4 overflow-x-auto my-3"><code className="text-xs font-mono text-gray-300">{children}</code></pre>,
                  blockquote: ({children}) => <blockquote className="border-l-4 border-accent-green/50 pl-4 py-1 my-3 text-gray-400 italic">{children}</blockquote>,
                  table: ({children}) => (
                    <div className="overflow-x-auto my-4">
                      <table className="w-full text-sm border-collapse">{children}</table>
                    </div>
                  ),
                  thead: ({children}) => <thead className="bg-dark-border/40">{children}</thead>,
                  tbody: ({children}) => <tbody className="divide-y divide-dark-border/30">{children}</tbody>,
                  tr: ({children}) => <tr className="hover:bg-dark-border/20 transition-colors">{children}</tr>,
                  th: ({children}) => <th className="px-4 py-2 text-left text-xs font-semibold text-accent-green uppercase tracking-wider border-b border-dark-border">{children}</th>,
                  td: ({children}) => <td className="px-4 py-2 text-gray-300 text-sm">{children}</td>,
                  a: ({href, children}) => <a href={href} className="text-accent-green hover:underline" target="_blank" rel="noreferrer">{children}</a>,
                }}
              >
                {expandedReport.report_markdown || 'No content available.'}
              </ReactMarkdown>
            </div>
          </motion.div>
        </motion.div>
      )}
    </div>
  )
}

export default Reports
